### ISSUE TITLE
JSONDecodeError when running script

### ISSUE THREAD

**Issue by totte174** [i30817/libretrofuzz#1]
Unable to use script because of error.
Maybe this is something to look into?
Attached debug message and playlist

[errorlibretrofuzz.txt](https://github.com/i30817/libretrofuzz/files/9365870/errorlibretrofuzz.txt)
[Atari - 2600 - Copy.txt](https://github.com/i30817/libretrofuzz/files/9365878/Atari.-.2600.-.Copy.txt)

**Comment by i30817** [comment]
That's the old format of playlists, current retroarch uses json.

You must be using a very old version, or haven't updated the playlist in at least a year. I think maybe two? ~~Try updating them, in settings->playlists->chose the system->refresh playlist.~~

~~If you can't, try to rescan.~~

I guess i can try to support this format, since it's not big deal.

**Comment by i30817** [comment]
Try to reinstall with 

`pip install --force-reinstall https://github.com/i30817/libretrofuzz/archive/master.zip`

and try again now. Should work if the playlist has no mistakes.

**Comment by i30817** [comment]
I updated the fix to also work with compressed playlists and old format, because that's a retroarch option, for some stupid reason.
