### ISSUE TITLE
Impossible to change CFG location

### ISSUE THREAD

**Issue by ectoplasm1** [i30817/libretrofuzz#4]
Hello there is no command to change the default CFG location. I even tried it I the .py file and it does not work.

**Comment by i30817** [comment]
It's the first and only argument without a command line switch. It's just often not needed because the program checks some default locations if it's not provided.

Note this program doesn't work on android on termux yet, because of some dependencies not being available.

It's possible you're having trouble with the cmd line path quoting in windows. Frankly I don't know how it works, last time I tried it in a windows 7 vm I never got it to work without going into the cfg directory if I recall correctly. Or placing a copy of the cfg on the default location. That's a windows problem though, it's not my fault the cmd line sucks. The problem happens because on the default RetroArch install it can use a directory name with a '-', and that needs to be quoted iirc. That problem ONLY happens if you need to provide a cfg path manually, letting the program default to 'c:/RetroArch-Win64/retroarch.cfg' works if that file exists. I tried single and double quotes and none worked. It's wild.

The windows default location is just the place that the retroarch standalone installer for windows chooses by default on the root of c, then if that doesn't work the APPDATA path with RetroArch dir then the file. You can see the default locations in the readme, help switch, or [the first few lines of code ](https://github.com/i30817/libretrofuzz/blob/main/libretrofuzz/__main__.py#L78)after the imports in the main program file if you're comfortable reading code and want to see more details.

That's just to try to find the default. The part that checks if the user gives a argument is using the typer library here : https://github.com/i30817/libretrofuzz/blob/main/libretrofuzz/__main__.py#L672

Note the default is the cfg if found from that earlier code. So if you're failing you either don't have a cfg on those locations and don't provide a valid file, or you do have one but provide a invalid file.

There is also a autocomplete that works in Linux and I hope may work in windows with tab, but I wouldn't hold my breath.

**Comment by i30817** [comment]
Btw, you didn't forget to add python to the path when installing python if on windows right? Also you kind of need to install this on pip for the 'readme experience'. 

To run from the git repository, you need poetry installed and calling 'poetry run libretro-fuzz' on the git repo and install the dependencies before (I forget how it's done, probably poetry update), it's not a simple script.

I just mention it because you mentioned running the script directly instead of the launcher programs that typer makes (libretro-fuzz and libretro-fuzzall).

**Comment by i30817** [comment]
Any news about this? I really think it's user error on your end. Currently I don't have a computer, just a android tablet so it's hard to do bugfixes and impossible to test them, but I remember this working. If the problem is the windows command line being terrible and needing a impossible quote in the middle of a path to escape '-', I can't do anything but suggest you install RA in the default places or cd to the cfg directory, or remove the -Win64 suffix from the install dir, before calling this program to workaround it.
