### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by Feathered-Serpent** [i30817/libretrofuzz#6]
Hey again

Seemingly another error occured on me now.  This time I don't have a clue, what is wrong (as file because the text is too long):
[error.txt](https://github.com/i30817/libretrofuzz/files/13064398/error.txt)

I currently let it run again to see, if I can repeat it. Takes a little bit though.

**Comment by i30817** [comment]
Nasty. I think I know what happened.

The code precaches normalized forms of the names of all the remote thumbnails names and the local thumbnails names before actually doing the fuzzy compare with those.

Well in fact, it precaches multiple versions of those for various reasons, but that's not important here.

What's important is that one of your local names only has illegal Characters, or characters that are deemed unimportant and culled from normalized forms or for the thumbnail names (windows can't represent certain characters besides the /  - only character Linux can't represent, and culled characters\words are often ommitted\rearranged so there are better matches without them)


```
'! (2002)(Booze Design - Oneway)': ('', '', [''], [''], ''),            │ │
│ │                  │   '!++ (199x)(20th Century Composers - Scoop)': (                         │ │
│ │                  │   │   '',                                                                 │ │
│ │                  │   │   '',                                                                 │ │
│ │                  │   │   [''],                                                               │ │
│ │                  │   │   [''],                                                               │ │
│ │                  │   │   ''                                                                  │ │
│ │                  │   ),



```

So when it finally goes off to find the ratio of similarity one of the tests is giving a slight advantage to names that have more common prefix characters in order when in the simplest normalized form, which is done by calculating the ratio of the simplest normalized forms of both games being considered, then dividing it by the total length of the name being considered. Obviously that length is zero if all characters are illegal.

**Comment by Feathered-Serpent** [comment]
But which file name is it, I should check and change? If it's on my side.

After I've run multiple times without --no-meta (somehow it always found a few more thumbnails to download, like it somehow didn't download them before), I now want to download the "rest" of them with --no-meta and --min 98 (just to be sure, I get the correct thumbs)

**Comment by i30817** [comment]
Its !++ (199x)(20th Century Composers - Scoop)

Probably.

No meta is dangerous because it increases the chance of false positives. It removes from consideration all the metadata between '()' tags.

I'm not blaming it for the bug, even if it allowed it to show though, it's still a bug.

**Comment by Feathered-Serpent** [comment]
> No meta is dangerous because it increases the chance of false positives. It removes from consideration all the metadata between '()' tags.

I noticed, when I at first only used --no-meta, as scores of 91 were more often very different names. So I deleted all the thumbnails I downloaded with --no-meta and now use --no-meta --min 98.

Hmm... I don't find that name in my directories:
```
D:\games>dir *!++* /a /b /s
File not found
```

Could it be, it comes from the libretto thumbnails repository?

Edit: ok I found it manually. I dunno why my command didn't listed it at the command line. I remove the line temporarily from the playlist file.

**Comment by i30817** [comment]
They're local. Could also be `'! (2002)(Booze Design - Oneway)': ('', '', [''], [''], ''), `

In fact you might have to change both.


Search for the strings inside the brackets instead of the ! or the +

Edit: glad you found it.

I'm wary of doing a release without testing or even running the code but might mess around the github interface manually to fix this and the other. Pretty annoying bugs.

Exclamation point and plus sign ARE (supposed to be) illegal in windows and thus libretro thumbnails (with some subtilities). If libretro has thumbnails for those you'd only find them with the metadata on. Or maybe I'm looking at outdated lists of illegal Characters and ntfs is different...

**Comment by i30817** [comment]
I also don't recommend using no meta (or the other false positive prone options, --before and --hack) with libretro-fuzzall (which I noticed you were using in the stacktrace) because MANY playlists are almost complete and perfect without it but have loads of false positives with it because of languages rereleases, for instance the psx or scummvm thumbnails. Instead you can run libretro-fuzzall once, then supplement it for a particular playlist with libretro-fuzz --no-meta.

You can also investigate the --limit option, sometimes it gives more thumbnails for the different categories of thumbnails if the uploader screwed up.

Scummvm only if you use the names picked up from the scummvm.ini with my other tool for creating scummvm ra playlists.

**Comment by Feathered-Serpent** [comment]
Well, my problem is, that the names of the ROMs are taken from TOSEC, and thus the names more often don't match within the 90% seemingly. That or there are just less thumbnails available than I thought would be :)

**Comment by i30817** [comment]
It's kind of both. I can understand using no meta for tosec yes, the non meta names are often similar enough to get something.

But only for those if your dumps are not completely tosec, and id still be wary of multiple releases.

If you want all the information run with `SHORT=1 libretro-fuzz --dry-run --verbose --limit 3`. You'll see that with --no-meta it will often choose.... poorly.

Dry run will prevent download but if you're running on a modern windows you should be able to click the emojis for boxart,screenshot and title to be linked to the thumbnails... which is better for both the server and you if you're doing experimentation.


You can also run it with the 'server' pointing to the already downloaded thumbnails with the python trick explained in the --address option which is trippy and won't give the exact same results but can be useful if you already have the repos for the thumbnails locally (some thumbnail contributors have) or just want to mess around and point it to the thumbnail dir of ra itself for whatever reason.

**Comment by Feathered-Serpent** [comment]
Like with N64 games, libretro-fuzz without any parameters causes this:
```
0/1417 successes 659/1417 failures
```
So I run the normal one until it doesn't find any more thumbnails, and only then I switch to no-meta to find some thumbnails for the other games.

As the cause if this issue was the filename with !++, should I close this one? And it seems, I will try that with the local server! I probably could download the thumbnails github locally and then let libretrofuzz run against that, which should be faster!

**Comment by i30817** [comment]
Leave it open, it's a real bug

**Comment by i30817** [comment]
Also about downloading the thumbnails GitHub...uhhhm it's.... big. Remember, you're not downloading just the current thumbnails but all history by default. There is a way to limit that to a chosen number of most recent revisions but I don't remember if that works for git subprojects like the console systems on libretro-thumbnails are.

Actually that might not be true for the GitHub interface master download, which is usually just the lastest. It will still be huge though and I'm no sure if GitHub the site will allow that download from the web interface.

**Comment by Feathered-Serpent** [comment]
I know, it's around 44GB. But that shouldn't be an issue. I'm cloning the repo right now as the instructions from https://github.com/libretro-thumbnails/libretro-thumbnails#readme

**Comment by i30817** [comment]
Ah, yes --depth works in subprojects then.

**Comment by i30817** [comment]
Also I've been thinking of using this to generate a semi complete set of thumbnails with scummvm.ini scummvm names to upload to libretro-thumbnails (for my other utility libretro-mkscumm-playlist to create a playlist with always available thumbnails).

This should be possible now (I don't have all games or all releases to do it manually) because a few months ago scummvm added a 'dump all possible version names of games' switch, which could be used to create a fake playlist then pointing it to the scummvm games thumbs in libretro-thumbnails that already more or less follow the pattern with --no-fail, --no-meta or lower --score. 

Unfortunately it didn't work on all older engines, especially scumm, which made me delay to see if they'll add it for those. Then my computer blew up.

**Comment by Feathered-Serpent** [comment]
The download is done and I run fuzz against the local http server now. But I have to say, I thought it would be much faster. Dunno if it's because of the SSD of the computer I'm running it from. Doesn't look faster than using the internet download right now. But at least I don't have to rely on the internet connection anymore.

![grafik](https://github.com/i30817/libretrofuzz/assets/72162369/b45f4d36-2e61-44a7-9f2b-dd4d603ef308)

Edit: for some reason this seem to differ depending on the system... good thing I'm patient! (and sorry for the offtopic...)

**Comment by i30817** [comment]
No idea about speed depending on systems. The normalization step depends on the number of the system thumbnails but it's already amortized before downloads even start. The fuzzy search should also depend on size, but the library used uses some tricks to make it faster (it cuts off unneeded comparasions).

In order to make sure the downloads can be cancelled or do not overwrite what they're reading (in case you're using the RetroArch thumbnail dir as 'address' with python), downloads always download for a temporary directory first, so that part always has a extra copy... however, it's setup to after that copy is done and not cancelled (which you can only do with the delay options, keeping pressing space to cancel instantly or esc to quit), that copy is moved over and not copied again (it would be only copied in most filesystems if it wasn't in the same drive\partition, which I prevent by placing the cache thumbnail dir in the same dir as the ra thumbnail dir to make sure they're in the same drive\partition).


Edit: also you probably should not use --filter if you try to use a address pointing to the local dir of of the ra thumbnails (a git download is fine, the problem only exists if it's the same dir for the server and ra dir). The problem is that for consistency, --filter always deletes the thumbnails it matched thumbnails for. 

In fact, `--filter "*"` deletes all local thumbnails for the current processed local system. This is a 'problem' if your server is pointing to the ra directory. It's fine if it's a git both because that tends not to be the ra thumb dir, and even if it is because you can restore git files easily with git reset.

**Comment by i30817** [comment]
You can also use dry run with even a local repository address if you want to avoid that copy altogether. It won't place the thumbnails in the ra dir but you could see if that's the warmup problem or something else.

**Comment by i30817** [comment]
I'm a bit curious about the filename you had in the game that caused this problem, because I'm pretty sure that last time I tried to create  a file with '!' or '+' on a windows file explorer it refused, but your labels (note this program uses playlist labels not playlist filenames, so they might have 'illegal' characters in those, the program replaces them by _ to compare to the libretro-thumbnails - except it also removes _ during normalization because it gets more matches that way, so it has this error).

Are you using TOSEC .dat files  with the manual scanner? Or maybe the automatic scanner. That's the only two ways I can think you're getting ! Into a label (it does make sense, the names from dats are often much better than the filename which is what you get with the manual scanner without dat file).

**Comment by i30817** [comment]
I think this one is fixed, since it's quite easy to avoid. But the other one I'm not so sure. I'll ask for a text and explain my rationale for the code in that issue.

**Comment by Feathered-Serpent** [comment]
Other than the reserved characters (see https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file) Windows takes most of the ASCII characters as file name:
![grafik](https://github.com/i30817/libretrofuzz/assets/72162369/2d5b8268-26b7-44bf-b942-a2620a66a7f3)

trying with the most current version now. 

Edit: somehow it seems to be (much) slower, if the playlist file is a huge one. It took four minutes to go from file names starting with B to C on this one:
![grafik](https://github.com/i30817/libretrofuzz/assets/72162369/b309ac6b-eafa-46df-80f2-18419698b2e9)
(I really should uncompress all playlist file again so I can look into them... cannot unzip that rzip under windows)
Then again, of course that python http server window only shows me the files asked for, not the ones, libretrofuzz might have skipped while working on the list. Not having a number at how fast the process should be.

Edit2:
and python.exe runs always at 25% cpu utilization, which is one of the four cores of the system I'm running it on.

**Comment by i30817** [comment]
As for the allowed characters... I'm actually confused. I checked again and my forbidden character list takes just the normal ones and the 'invisible' ones that go from 0 to 31 as usual. Neither ! or + are supposed to be removed. More investigation might be required, even if the bug won't happen again.... later

**Comment by i30817** [comment]
Ok, found the reason. It's because during normalization I remove almost all punctuation symbols, except some used as markers for pronouns to remove, which I remove later anyway.

https://github.com/i30817/libretrofuzz/blob/d08316a4af70fa62b2ef778fbf98314687cc6a95/libretrofuzz/__main__.py#L393


This is because it gives many more matches to eliminate the symbols (and definite articles, and words like 'and', 'the' and such) when testing name variants.
Unless the name is all symbol I guess. I think I'll check if the resulting string is completely empty when eliminating these symbols and back out if so.

I think I won't bother when removing the 'remaining' symbols not removed then later because those symbols are the comma and ’

Names with just those two are lost causes.

Personally I rather doubt the libretro thumbnails servers have thumbnails for '!' and '!++' (the server doesn't bother with demos. Edit: they don't exist there) but I guess it's better to be possible than impossible.

**Comment by i30817** [comment]
Closed for real now, any complaint please post

**Comment by i30817** [comment]
@Feathered-Serpent testing with your large commodore playlist, I believe I managed to make the fuzz sorting faster. Had to replace WRatio by QRatio, which is slightly lower quality but I believe it makes little difference with how I'm using the scoring function. Also increased the speed of normalization slightly again.

I expect it would take several hours even with the new faster code. Been a hour here and I'm just at 'Ar'. In the shitty 2018 tablet admittedly.

Even then I actually think it's kind of a bad idea to use this for TOSEC+goodtools complete dumps. The playlist you gave had dozens on dozens of same game entries that just changed the hacking group. At least you should use a file dedup tool that can replace duplicate files by symbolic links like for instance, https://github.com/pkolaczk/fclones/releases (id actually like to depend on something cool like that, to run at the end of all downloads, but it's probably better to leave that to users). Tools like this won't work on RetroArch for android\termux too, because android is paranoid and disabled symlink and hardlinks creation (outside a application sandbox anyway, and RetroArch doesn't put its thumbnails on a sandbox and even if it did we don't have a good way to run things there without creating a whole core 😂)

Imo, no intro all the way.

**Comment by i30817** [comment]
I'm thinking it might be possible to use multiprocessing again to divide and conquer the game label fuzz for more speed too, but then you probably lose the order... Not sure I care though.

**Comment by Feathered-Serpent** [comment]
> Even then I actually think it's kind of a bad idea to use this for TOSEC+goodtools complete dumps. The playlist you gave had dozens on dozens of same game entries that just changed the hacking group. 

I already have deleted every file with the Tags Alternate, Bad Dump, Hacked, Modified, Pirated, Overdumped, Underdumped and Virus. I guess I also should have removed any [cr-ones if you mean that ones. Might have missed that. (oh and I deleted every file not marked as English or German or translated to English or German)

Now I'm done with thumbnail downloading and I wasn't sure if I should bother with it. I actually programmed me a batch file so every system is run 10 times for thumbnails, and 10 times with -no-meta, because I had runs where on the same system at the seventh run it still found some thumbnails, which it somehow not found before. After 10 runs without -no-meta and 10 runs with, I'm fine with the amount of thumbnails now.

**Comment by i30817** [comment]
I've also noticed those variable results sometimes. It's difficult to figure out considering how it's affected by the playlist and a server, but I suspect the search is not stable, especially with the normalizer and nometa turning several names effectively identical for fuzzy matching purpose (note that there is no alternative afaik to increase matches).

But even so I kind of suspect my scorer function is itself temperamental with the way it zooms into subtitles that match exactly a name and gives them a bump. I don't _think_ rapidfuzz depends on scoring transitivity though.

Maybe I should try to sort identical winning matches by their original name instead of restricting the limit right at the start (rapidfuzz does a little optimization if the limit is 1 though).

I tried ProcessPoolExecutor for the fuzzy matching and it increases latency unacceptably. I think QRatio is enough speed for that part for now, doesn't feel terrible on a tablet device from 2018.
